filebeat.prospectors:
- type: log
  enabled: true
  tags:
    - netflower
  paths:
    - /home/brayan/PycharmProjects/pythonProject/logs/*.log

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "127.0.0.1:5601"

output.kafka:
  hosts: ["127.0.0.1:9092"]
  topic: 'filebeat'
  partition.round_robin:
    reachable_only: false
  codec.format:
    string: '%{[id]:none},%{[name]:none},%{[age]:none}'
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  close_inactive: 10m

processors:
 - decode_json_fields:
     fields: ["message","id","name","age"]
     process_array: false
     max_depth: 1
     target: ""
     overwrite_keys: false

seccomp:
  default_action: allow 
  syscalls:
  - action: allow
    names:
    - rseq

